version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo "Installing dependencies..."
      - npm install
  build:
    commands:
      - echo "Running build..."
      - npm run build || echo "No build step, skipping..."
artifacts:
  files:
    - '**/*'
    - '!node_modules/**'   # exclude node_modules, EB will install them
